targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/api/swagger'
          output_folder: 'lib/api/generated'
          separate_models: true
          ignore_header: false
